# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact: windows.complog
          - os: ubuntu-latest
            artifact: ubuntu.complog

    name: Build and Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -bl
    - name: Test
      run: dotnet test --no-build --verbosity normal --framework net7.0
      if: matrix.os == 'ubuntu-latest'
    - name: Test
      run: dotnet test --no-build --verbosity normal
      if: matrix.os == 'windows-latest'
    - name: Create Compiler Log
      run: dotnet run --project src/Basic.CompilerLog/Basic.CompilerLog.csproj create msbuild.binlog
    - name: Publish Compiler Log
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact }}
        path: msbuild.complog
